apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-load-test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/StephaneFotso/pkz-platform-load-test
    targetRevision: main
    path: workloads-load-tests

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
