apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads
spec:
  source:
    repoURL: https://github.com/org/repo.git
    path: .
    helm:
      valueFiles:
        - products/product-001.yaml
        - products/product-002.yaml
        # généré dynamiquement
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
